#!/bin/sh
# 静态证明关键 AWS 边界存在；可传入复制后的目录供危险变体负测。
set -eu

script_directory=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
terraform_root=${1:-$(CDPATH='' cd -- "$script_directory/.." && pwd)}

fail() {
  printf '%s\n' "Terraform static contract: $*" >&2
  exit 1
}

require_file() {
  test -f "$terraform_root/$1" || fail "缺少 $1"
}

require_text() {
  pattern=$1
  file=$2
  grep -F "$pattern" "$terraform_root/$file" >/dev/null || fail "$file 缺少契约: $pattern"
}

require_line_pattern() {
  pattern=$1
  file=$2
  grep -E "$pattern" "$terraform_root/$file" >/dev/null || fail "$file 缺少行契约: $pattern"
}

require_line_pattern_count() {
  expected=$1
  pattern=$2
  file=$3
  actual=$(grep -E -c "$pattern" "$terraform_root/$file" || true)
  test "$actual" -eq "$expected" || fail "${file} 中行契约数量错误: ${pattern}，预期 ${expected}，实际 ${actual}"
}

require_count() {
  expected=$1
  pattern=$2
  file=$3
  actual=$(grep -F -c "$pattern" "$terraform_root/$file" || true)
  test "$actual" -eq "$expected" || fail "${file} 中契约数量错误: ${pattern}，预期 ${expected}，实际 ${actual}"
}

forbid_text() {
  pattern=$1
  file=$2
  if grep -F "$pattern" "$terraform_root/$file" >/dev/null; then
    fail "$file 包含被禁止的契约: $pattern"
  fi
}

for environment in dev staging prod-primary prod-dr; do
  require_file "environments/$environment/main.tf"
  require_file "environments/$environment/backend.example.hcl"
  require_file "environments/$environment/terraform.tfvars.example"
  require_file "environments/$environment/.terraform.lock.hcl"
  require_text 'allowed_account_ids = [var.configuration.expected_account_id]' "environments/$environment/main.tf"
  require_text 'use_lockfile = true' "environments/$environment/main.tf"
  require_text 'version = "= 6.57.1"' "environments/$environment/main.tf"
  require_text 'variable "valkey_password_a"' "environments/$environment/main.tf"
  require_text 'variable "valkey_password_b"' "environments/$environment/main.tf"
  require_text 'valkey_password_a         = var.valkey_password_a' "environments/$environment/main.tf"
  require_text 'valkey_password_b         = var.valkey_password_b' "environments/$environment/main.tf"
  require_text 'valkey_active_slot' "environments/$environment/terraform.tfvars.example"
  require_text 'valkey_rotation_mode' "environments/$environment/terraform.tfvars.example"
  require_text 'valkey_password_version_a' "environments/$environment/terraform.tfvars.example"
  require_text 'valkey_password_version_b' "environments/$environment/terraform.tfvars.example"
  require_text 'valkey_password_reset_approvals = {}' "environments/$environment/terraform.tfvars.example"
  require_text 'waf_rollout_evidence_kms_key_arn' "environments/$environment/terraform.tfvars.example"
  require_text 'api_waf_managed_rule_versions' "environments/$environment/terraform.tfvars.example"
  require_text 'cloudfront_waf_managed_rule_versions' "environments/$environment/terraform.tfvars.example"
  require_text 'valkey_hmac_maintenance_approval = null' "environments/$environment/terraform.tfvars.example"
  require_text 'rds_alarm_thresholds = {' "environments/$environment/terraform.tfvars.example"
  require_count 3 'cpu_utilization_percent' "environments/$environment/terraform.tfvars.example"
  require_count 2 'database_connections' "environments/$environment/terraform.tfvars.example"
  require_count 2 'freeable_memory_bytes' "environments/$environment/terraform.tfvars.example"
  require_count 2 'free_storage_space_bytes' "environments/$environment/terraform.tfvars.example"
  require_count 2 'read_latency_seconds' "environments/$environment/terraform.tfvars.example"
  require_text 'write_latency_seconds' "environments/$environment/terraform.tfvars.example"
  require_count 2 'disk_queue_depth' "environments/$environment/terraform.tfvars.example"
  require_text 'deadlocks_per_minute     = 1' "environments/$environment/terraform.tfvars.example"
  require_text 'total_iops_per_second' "environments/$environment/terraform.tfvars.example"
  require_text 'total_throughput_bytes_per_second' "environments/$environment/terraform.tfvars.example"
  forbid_text 'read_iops_per_second' "environments/$environment/terraform.tfvars.example"
  forbid_text 'write_iops_per_second' "environments/$environment/terraform.tfvars.example"
  require_count 2 'swap_usage_bytes' "environments/$environment/terraform.tfvars.example"
  require_text 'valkey_alarm_thresholds = {' "environments/$environment/terraform.tfvars.example"
  require_text 'engine_cpu_utilization_percent' "environments/$environment/terraform.tfvars.example"
  require_text 'database_capacity_usage_counted_for_evict_percent' "environments/$environment/terraform.tfvars.example"
  require_text 'current_connections' "environments/$environment/terraform.tfvars.example"
  require_text 'replication_lag_seconds' "environments/$environment/terraform.tfvars.example"
  require_text 'eval_based_commands_latency_microseconds' "environments/$environment/terraform.tfvars.example"
  require_text 'api_waf_rate_limits = {' "environments/$environment/terraform.tfvars.example"
  require_text 'public_requests_per_minute' "environments/$environment/terraform.tfvars.example"
  require_text 'spin_requests_per_minute' "environments/$environment/terraform.tfvars.example"
  require_text 'launch_requests_per_minute' "environments/$environment/terraform.tfvars.example"
  require_text 'api_waf_rate_rule_rollouts = {' "environments/$environment/terraform.tfvars.example"
  require_text 'launch-rate-limit = {' "environments/$environment/terraform.tfvars.example"
  require_text 'public-api-rate-limit = {' "environments/$environment/terraform.tfvars.example"
  require_text 'spin-rate-limit = {' "environments/$environment/terraform.tfvars.example"
  require_text 'api_waf_alarm_thresholds = {' "environments/$environment/terraform.tfvars.example"
  require_text 'api_waf_managed_rule_rollout = {' "environments/$environment/terraform.tfvars.example"
  require_text 'cloudfront_waf_rate_limit_per_minute' "environments/$environment/terraform.tfvars.example"
  require_text 'cloudfront_waf_rate_rule_rollout = {' "environments/$environment/terraform.tfvars.example"
  require_text 'cloudfront_waf_log_group_name' "environments/$environment/terraform.tfvars.example"
  require_text 'cloudfront_waf_managed_rule_rollout = {' "environments/$environment/terraform.tfvars.example"
  require_count 7 'action             = "count"' "environments/$environment/terraform.tfvars.example"
  require_count 7 'evidence_reference = "observation-pending"' "environments/$environment/terraform.tfvars.example"
  require_text 'application_namespace' "environments/$environment/terraform.tfvars.example"
  require_text 'helm_release_name' "environments/$environment/terraform.tfvars.example"
done

require_file 'contracts/landing-zone-interface.v1.yaml'
require_file 'contracts/cluster-addons-interface.v1.yaml'
require_file 'scripts/verify-valkey-rotation-plan.rb'
require_file 'scripts/test-valkey-rotation-plan.rb'
test -x "$terraform_root/scripts/verify-valkey-rotation-plan.rb" || fail 'Valkey plan 门禁不可执行'
test -x "$terraform_root/scripts/test-valkey-rotation-plan.rb" || fail 'Valkey plan 状态机测试不可执行'
require_text 'ruby "$script_directory/test-valkey-rotation-plan.rb"' 'scripts/verify.sh'
require_text 'contractVersion: 1.0.0' 'contracts/landing-zone-interface.v1.yaml'
require_text 'iam:GetRolePolicy' 'contracts/landing-zone-interface.v1.yaml'
require_text 'cloudfront:GetResponseHeadersPolicyConfig' 'contracts/landing-zone-interface.v1.yaml'
require_text 's3:GetObjectVersion' 'contracts/landing-zone-interface.v1.yaml'
require_text 's3:GetBucketPublicAccessBlock' 'contracts/landing-zone-interface.v1.yaml'
require_text 's3:GetBucketPolicy' 'contracts/landing-zone-interface.v1.yaml'
require_count 3 's3:GetObjectVersion' 'contracts/landing-zone-interface.v1.yaml'
require_count 2 's3:GetObjectRetention' 'contracts/landing-zone-interface.v1.yaml'
require_text 'wafBlockPromotionEvidenceReadActions:' 'contracts/landing-zone-interface.v1.yaml'
require_text 'elasticloadbalancing:DescribeTargetHealth' 'contracts/landing-zone-interface.v1.yaml'
require_text 'elasticloadbalancing:DescribeRules' 'contracts/landing-zone-interface.v1.yaml'
require_text 'eks:DescribeAddon' 'contracts/landing-zone-interface.v1.yaml'
require_text 'eks:DescribePodIdentityAssociation' 'contracts/landing-zone-interface.v1.yaml'
require_text 'eks:ListPodIdentityAssociations' 'contracts/landing-zone-interface.v1.yaml'
require_text 'ec2:DescribeSecurityGroupRules' 'contracts/landing-zone-interface.v1.yaml'
require_text 'wafv2:GetWebACLForResource' 'contracts/landing-zone-interface.v1.yaml'
require_text 'elasticache:DescribeCacheClusters' 'contracts/landing-zone-interface.v1.yaml'
require_text 'elasticache:DescribeCacheParameters' 'contracts/landing-zone-interface.v1.yaml'
require_text 'elasticache:DescribeReplicationGroups' 'contracts/landing-zone-interface.v1.yaml'
require_text 'logs:DescribeMetricFilters' 'contracts/landing-zone-interface.v1.yaml'
require_text 'rds:DescribeDBInstances' 'contracts/landing-zone-interface.v1.yaml'
require_text 'eksAccessAllowedForHmacMaintenance: false' 'contracts/landing-zone-interface.v1.yaml'
require_text 'authoritativePublicEntry: internet-facing-alb' 'contracts/landing-zone-interface.v1.yaml'
require_text 'cloudFrontProxy: false' 'contracts/landing-zone-interface.v1.yaml'
require_text 'sourceBypassModel: not-applicable-alb-is-authoritative-origin' 'contracts/landing-zone-interface.v1.yaml'
require_text 'unknownPathOrMethodAction: block-at-waf' 'contracts/landing-zone-interface.v1.yaml'
require_text 'headerOversizeDefaultAction: count' 'contracts/landing-zone-interface.v1.yaml'
require_text 'lowRateRulesExactNewIntentPathsOnly: true' 'contracts/landing-zone-interface.v1.yaml'
require_text 'statusResultAckExcludedFromLowRateRules: true' 'contracts/landing-zone-interface.v1.yaml'
require_text 'publicApiHighRateRuleStillApplies: true' 'contracts/landing-zone-interface.v1.yaml'
require_text 'optionsPreflightCoveredByHighRateRule: true' 'contracts/landing-zone-interface.v1.yaml'
require_text 'accessControlExposeHeaders: "Retry-After, X-RGS-Edge-Error"' 'contracts/landing-zone-interface.v1.yaml'
require_text 'markerValue: RATE_LIMITED' 'contracts/landing-zone-interface.v1.yaml'
require_text 'sourceIpRateRulesAreNotIdentityAuthority: true' 'contracts/landing-zone-interface.v1.yaml'
require_count 2 'stagedRulesRequireImmutableCalibrationEvidence: true' 'contracts/landing-zone-interface.v1.yaml'
require_count 2 'blockPromotionReadsExactS3ObjectVersion: true' 'contracts/landing-zone-interface.v1.yaml'
require_count 2 'blockPromotionVerifiesContentSha256: true' 'contracts/landing-zone-interface.v1.yaml'
require_count 2 'blockPromotionValidatesRuleBoundApprovalSchema: true' 'contracts/landing-zone-interface.v1.yaml'
require_count 2 'wafLogsRedactQueryString: true' 'contracts/landing-zone-interface.v1.yaml'
require_count 2 'sampledRequestsEnabled: false' 'contracts/landing-zone-interface.v1.yaml'
require_count 2 'blockPromotionRequiresApprovedKmsKey: true' 'contracts/landing-zone-interface.v1.yaml'
require_count 2 'blockPromotionRequiresComplianceObjectLock: true' 'contracts/landing-zone-interface.v1.yaml'
require_count 2 'managedRuleVersionsPinned: true' 'contracts/landing-zone-interface.v1.yaml'
require_text 'shieldAdvancedRequiresExplicitCostApproval: true' 'contracts/landing-zone-interface.v1.yaml'
require_text 'noneMayBeClaimedWithoutLiveEvidence: true' 'contracts/landing-zone-interface.v1.yaml'
require_text 'applyMeansApplicationReady: false' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'requiresPrivateVpcRunner: true' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'requiredBeforeHelmUpgrade: true' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'expected_account_id' 'modules/delivery-contract/variables.tf'
require_text 'bootstrap_cluster_creator_admin_permissions = false' 'modules/eks/main.tf'
require_text 'endpoint_public_access  = false' 'modules/eks/main.tf'
require_text 'http_tokens                 = "required"' 'modules/eks/main.tf'
require_text 'ignore_changes = [scaling_config[0].desired_size]' 'modules/eks/main.tf'
require_count 1 'ignore_changes = [scaling_config[0].desired_size]' 'modules/eks/main.tf'
require_text 'min_size     = var.node_min_size' 'modules/eks/main.tf'
require_text 'max_size     = var.node_max_size' 'modules/eks/main.tf'
forbid_text 'ignore_changes = [scaling_config]' 'modules/eks/main.tf'
require_text 'resource "aws_eks_pod_identity_association" "cluster_autoscaler"' 'modules/eks/main.tf'
require_text 'service_account = "cluster-autoscaler"' 'modules/eks/main.tf'
require_text 'aws:RequestTag/kubernetes-service-account' 'modules/eks/main.tf'
require_text 'autoscaling:SetDesiredCapacity' 'modules/eks/main.tf'
require_text '"autoscaling:DescribeTags"' 'modules/eks/main.tf'
forbid_text '"autoscaling:*"' 'modules/eks/main.tf'
require_text 'aws:ResourceTag/k8s.io/cluster-autoscaler/${var.name_prefix}' 'modules/eks/main.tf'
require_text '"k8s.io/cluster-autoscaler/${var.name_prefix}" = "owned"' 'modules/eks/main.tf'
require_text 'addon_version = var.cloudwatch_addon_version' 'modules/observability/main.tf'
require_text 'AWSServiceRoleForAutoScaling' 'modules/kms/main.tf'
require_text 'kms:GrantIsForAWSResource' 'modules/kms/main.tf'
require_text 'kms:EncryptionContext:aws:logs:arn' 'modules/kms/main.tf'
require_text 'prevent_destroy = true' 'modules/kms/main.tf'
require_count 2 'publicly_accessible    = false' 'modules/rds/main.tf'
require_text 'prevent_destroy = true' 'modules/rds/main.tf'
require_text 'manage_master_user_password   = true' 'modules/rds/main.tf'
require_text 'name              = "/aws/rds/instance/${local.identifier}/${each.key}"' 'modules/rds/main.tf'
require_count 2 'kms_key_id        = var.log_kms_key_arn' 'modules/rds/main.tf'
require_text 'var.parameter_group_family == "postgres${split(".", var.engine_version)[0]}"' 'modules/rds/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "capacity_high"' 'modules/rds/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "capacity_low"' 'modules/rds/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "total_iops"' 'modules/rds/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "total_throughput"' 'modules/rds/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "deadlocks"' 'modules/rds/main.tf'
require_text 'resource "aws_cloudwatch_log_metric_filter" "deadlocks"' 'modules/rds/main.tf'
require_text 'for_each = local.capacity_high_alarm_metrics' 'modules/rds/main.tf'
require_text 'for_each = local.capacity_low_alarm_metrics' 'modules/rds/main.tf'
require_count 5 'namespace           = "AWS/RDS"' 'modules/rds/main.tf'
require_count 4 'namespace   = "AWS/RDS"' 'modules/rds/main.tf'
require_text 'deadlock_filter_pattern   = "\"deadlock detected\""' 'modules/rds/main.tf'
require_text 'deadlock_metric_namespace = "Slots/RDSLogEvents"' 'modules/rds/main.tf'
require_text 'log_group_name = aws_cloudwatch_log_group.this["postgresql"].name' 'modules/rds/main.tf'
require_text 'pattern        = local.deadlock_filter_pattern' 'modules/rds/main.tf'
require_text 'name          = local.deadlock_metric_name' 'modules/rds/main.tf'
require_text 'namespace     = local.deadlock_metric_namespace' 'modules/rds/main.tf'
require_text 'value         = "1"' 'modules/rds/main.tf'
require_text 'default_value = 0' 'modules/rds/main.tf'
require_text 'unit          = "Count"' 'modules/rds/main.tf'
require_text 'namespace           = local.deadlock_metric_namespace' 'modules/rds/main.tf'
require_text 'metric_name         = local.deadlock_metric_name' 'modules/rds/main.tf'
require_text 'depends_on = [aws_cloudwatch_log_metric_filter.deadlocks]' 'modules/rds/main.tf'
require_count 2 'metric_name = "CPUUtilization"' 'modules/rds/main.tf'
require_count 2 'metric_name = "DatabaseConnections"' 'modules/rds/main.tf'
require_count 2 'metric_name = "FreeableMemory"' 'modules/rds/main.tf'
require_count 2 'metric_name = "FreeStorageSpace"' 'modules/rds/main.tf'
require_count 2 'metric_name = "ReadLatency"' 'modules/rds/main.tf'
require_text 'metric_name = "WriteLatency"' 'modules/rds/main.tf'
require_count 2 'metric_name = "DiskQueueDepth"' 'modules/rds/main.tf'
require_text 'metric_name = "ReadIOPS"' 'modules/rds/main.tf'
require_text 'metric_name = "WriteIOPS"' 'modules/rds/main.tf'
require_text 'metric_name = "ReadThroughput"' 'modules/rds/main.tf'
require_text 'metric_name = "WriteThroughput"' 'modules/rds/main.tf'
require_count 2 'metric_name = "SwapUsage"' 'modules/rds/main.tf'
forbid_text 'metric_name         = "Deadlocks"' 'modules/rds/main.tf'
require_text 'metric_name         = "ReplicaLag"' 'modules/rds/main.tf'
require_count 5 'statistic   = "Average"' 'modules/rds/main.tf'
require_count 4 'stat        = "Average"' 'modules/rds/main.tf'
require_count 6 'statistic   = "Maximum"' 'modules/rds/main.tf'
require_count 4 'statistic   = "Minimum"' 'modules/rds/main.tf'
require_text 'statistic           = "Sum"' 'modules/rds/main.tf'
require_count 4 'unit                = each.value.unit' 'modules/rds/main.tf'
require_count 2 'unit        = "Count/Second"' 'modules/rds/main.tf'
require_count 2 'unit        = "Bytes/Second"' 'modules/rds/main.tf'
require_count 6 'unit        = "Bytes"' 'modules/rds/main.tf'
require_text 'unit                = "Count"' 'modules/rds/main.tf'
require_count 7 'datapoints_to_alarm = 2' 'modules/rds/main.tf'
require_count 7 'evaluation_periods  = 3' 'modules/rds/main.tf'
require_text 'datapoints_to_alarm = 1' 'modules/rds/main.tf'
require_text 'evaluation_periods  = 1' 'modules/rds/main.tf'
require_count 6 'period              = 60' 'modules/rds/main.tf'
require_count 4 'period      = 60' 'modules/rds/main.tf'
require_count 7 'treat_missing_data  = "notBreaching"' 'modules/rds/main.tf'
require_text 'treat_missing_data  = "breaching"' 'modules/rds/main.tf'
require_count 8 'alarm_actions       = [var.alert_topic_arn]' 'modules/rds/main.tf'
require_count 8 'ok_actions          = [var.alert_topic_arn]' 'modules/rds/main.tf'
require_count 6 'DBInstanceIdentifier = aws_db_instance.this.identifier' 'modules/rds/main.tf'
require_count 6 'comparison_operator = "GreaterThanOrEqualToThreshold"' 'modules/rds/main.tf'
require_count 2 'comparison_operator = "LessThanOrEqualToThreshold"' 'modules/rds/main.tf'
require_count 2 'expression  = "m1 + m2"' 'modules/rds/main.tf'
require_count 2 'id          = "e1"' 'modules/rds/main.tf'
require_count 2 'id          = "m1"' 'modules/rds/main.tf'
require_count 2 'id          = "m2"' 'modules/rds/main.tf'
require_count 2 'return_data = true' 'modules/rds/main.tf'
require_count 4 'return_data = false' 'modules/rds/main.tf'
require_text 'threshold   = var.alarm_thresholds.cpu_utilization_percent' 'modules/rds/main.tf'
require_text 'threshold   = var.alarm_thresholds.database_connections' 'modules/rds/main.tf'
require_text 'threshold   = var.alarm_thresholds.freeable_memory_bytes' 'modules/rds/main.tf'
require_text 'threshold   = var.alarm_thresholds.free_storage_space_bytes' 'modules/rds/main.tf'
require_text 'threshold   = var.alarm_thresholds.read_latency_seconds' 'modules/rds/main.tf'
require_text 'threshold   = var.alarm_thresholds.write_latency_seconds' 'modules/rds/main.tf'
require_text 'threshold   = var.alarm_thresholds.disk_queue_depth' 'modules/rds/main.tf'
require_text 'threshold           = var.alarm_thresholds.total_iops_per_second' 'modules/rds/main.tf'
require_text 'threshold           = var.alarm_thresholds.total_throughput_bytes_per_second' 'modules/rds/main.tf'
require_text 'threshold   = var.alarm_thresholds.swap_usage_bytes' 'modules/rds/main.tf'
require_text 'threshold           = var.alarm_thresholds.deadlocks_per_minute' 'modules/rds/main.tf'
require_text 'var.alarm_thresholds.cpu_utilization_percent <= 100' 'modules/rds/variables.tf'
require_text 'var.alarm_thresholds.database_connections <= 1000000' 'modules/rds/variables.tf'
require_text 'floor(var.alarm_thresholds.freeable_memory_bytes) == var.alarm_thresholds.freeable_memory_bytes' 'modules/rds/variables.tf'
require_text 'floor(var.alarm_thresholds.free_storage_space_bytes) == var.alarm_thresholds.free_storage_space_bytes' 'modules/rds/variables.tf'
require_text 'var.alarm_thresholds.read_latency_seconds <= 60' 'modules/rds/variables.tf'
require_text 'var.alarm_thresholds.write_latency_seconds <= 60' 'modules/rds/variables.tf'
require_text 'var.alarm_thresholds.disk_queue_depth <= 1000000' 'modules/rds/variables.tf'
require_text 'var.alarm_thresholds.deadlocks_per_minute == 1' 'modules/rds/variables.tf'
require_text 'floor(var.alarm_thresholds.total_iops_per_second) == var.alarm_thresholds.total_iops_per_second' 'modules/rds/variables.tf'
require_text 'var.alarm_thresholds.total_throughput_bytes_per_second <= 1000000000000000' 'modules/rds/variables.tf'
require_text 'var.alarm_thresholds.swap_usage_bytes >= 1048576' 'modules/rds/variables.tf'
forbid_text 'read_iops_per_second' 'modules/rds/variables.tf'
forbid_text 'write_iops_per_second' 'modules/rds/variables.tf'
require_text 'variable "read_replica"' 'modules/rds/variables.tf'
require_text 'enabled        = false' 'modules/rds/variables.tf'
require_text '!var.read_replica.enabled || (' 'modules/rds/variables.tf'
require_text 'var.read_replica.alarm_thresholds.replica_lag_seconds <= 3600' 'modules/rds/variables.tf'
require_text 'resource "aws_db_instance" "reader"' 'modules/rds/main.tf'
require_count 2 'count = var.read_replica.enabled ? 1 : 0' 'modules/rds/main.tf'
require_text 'replicate_source_db = aws_db_instance.this.arn' 'modules/rds/main.tf'
require_count 2 'db_subnet_group_name   = aws_db_subnet_group.this.name' 'modules/rds/main.tf'
require_count 2 'vpc_security_group_ids = [aws_security_group.this.id]' 'modules/rds/main.tf'
require_count 1 'parameter_group_name   = aws_db_parameter_group.this.name' 'modules/rds/main.tf'
require_count 1 '  kms_key_id            = var.kms_key_arn' 'modules/rds/main.tf'
require_text 'backup_retention_period = var.backup_retention_days' 'modules/rds/main.tf'
require_count 2 'deletion_protection                 = var.deletion_protection' 'modules/rds/main.tf'
require_count 2 'prevent_destroy = true' 'modules/rds/main.tf'
require_text 'tonumber(split(".", var.engine_version)[0]) > 14' 'modules/rds/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "reader_capacity_high"' 'modules/rds/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "reader_capacity_low"' 'modules/rds/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "reader_replica_lag"' 'modules/rds/main.tf'
require_count 3 'DBInstanceIdentifier = aws_db_instance.reader[0].identifier' 'modules/rds/main.tf'
require_text 'var.rds_alarm_thresholds.deadlocks_per_minute == 1' 'stacks/application-platform/variables.tf'
require_text 'alarm_thresholds          = var.rds_alarm_thresholds' 'stacks/application-platform/main.tf'
require_text 'read_replica              = var.rds_read_replica' 'stacks/application-platform/main.tf'
require_text '(!var.rds_read_replica.enabled || var.rds_read_replica.multi_az)' 'stacks/application-platform/main.tf'
require_text 'rds_alarm_thresholds                  = var.configuration.rds_alarm_thresholds' 'stacks/environment/main.tf'
require_line_pattern '^[[:space:]]*rds_read_replica[[:space:]]*=[[:space:]]*try[(]var[.]configuration[.]rds_read_replica,[[:space:]]*[{][[:space:]]*$' 'stacks/environment/main.tf'
require_text 'output "alarm_contract"' 'modules/rds/outputs.tf'
require_text 'database_topology      = "single-db-instance"' 'modules/rds/outputs.tf'
require_text 'contract_version       = "2.0.0"' 'modules/rds/outputs.tf'
require_text 'TotalIOPS = {' 'modules/rds/outputs.tf'
require_text 'TotalThroughput = {' 'modules/rds/outputs.tf'
require_count 2 'expression  = "m1 + m2"' 'modules/rds/outputs.tf'
require_count 2 'return_data = true' 'modules/rds/outputs.tf'
require_line_pattern_count 4 '^[[:space:]]*return_data[[:space:]]*=[[:space:]]*false[[:space:]]*$' 'modules/rds/outputs.tf'
require_text 'deadlock_metric_filter = {' 'modules/rds/outputs.tf'
require_text 'filter_name      = aws_cloudwatch_log_metric_filter.deadlocks.name' 'modules/rds/outputs.tf'
require_text 'filter_pattern   = aws_cloudwatch_log_metric_filter.deadlocks.pattern' 'modules/rds/outputs.tf'
require_text 'metric_namespace = local.deadlock_metric_namespace' 'modules/rds/outputs.tf'
require_text 'default_value    = 0' 'modules/rds/outputs.tf'
require_text 'automatic_snapshot_implemented      = false' 'modules/rds/outputs.tf'
require_text 'external_evidence_consumer_required = true' 'modules/rds/outputs.tf'
require_text 'output "reader_endpoint"' 'modules/rds/outputs.tf'
require_text 'output "read_scaling_contract"' 'modules/rds/outputs.tf'
require_text 'application_routing_adopted     = false' 'modules/rds/outputs.tf'
require_text 'connection_pooler_implemented   = false' 'modules/rds/outputs.tf'
require_text 'rds_proxy_implemented           = false' 'modules/rds/outputs.tf'
require_text 'cross_region_dr_implemented     = false' 'modules/rds/outputs.tf'
require_text 'read_replica_is_backup          = false' 'modules/rds/outputs.tf'
require_text 'same_region_kms_inheritance     = true' 'modules/rds/outputs.tf'
require_text 'live_inheritance_check_required = var.read_replica.enabled' 'modules/rds/outputs.tf'
require_text 'engine_version                  = var.read_replica.enabled ? var.engine_version : null' 'modules/rds/outputs.tf'
require_text 'instance_class                  = var.read_replica.enabled ? var.read_replica.instance_class : null' 'modules/rds/outputs.tf'
require_text 'storage_type                    = var.read_replica.enabled ? "gp3" : null' 'modules/rds/outputs.tf'
require_text 'minimum_allocated_storage_gib   = var.read_replica.enabled ? var.allocated_storage_gib : null' 'modules/rds/outputs.tf'
require_text 'max_allocated_storage_gib       = var.read_replica.enabled ? var.max_allocated_storage_gib : null' 'modules/rds/outputs.tf'
for production_environment in environments/prod-primary/terraform.tfvars.example environments/prod-dr/terraform.tfvars.example; do
  require_text 'rds_allocated_storage_gib     = 500' "$production_environment"
  require_text 'total_iops_per_second             = 9600' "$production_environment"
  require_text 'total_throughput_bytes_per_second = 419430400' "$production_environment"
done
for environment in dev staging prod-primary prod-dr; do
  require_text 'rds_read_replica = {' "environments/$environment/terraform.tfvars.example"
  require_text 'enabled        = false' "environments/$environment/terraform.tfvars.example"
done
require_text 'output "rds_alarm_contract"' 'stacks/application-platform/outputs.tf'
require_text 'value       = module.rds.alarm_contract' 'stacks/application-platform/outputs.tf'
require_text 'output "rds_reader_endpoint"' 'stacks/application-platform/outputs.tf'
require_text 'output "rds_read_scaling_contract"' 'stacks/application-platform/outputs.tf'
require_text 'rds_reader_endpoint                       = module.platform.rds_reader_endpoint' 'stacks/environment/outputs.tf'
require_text 'rds_read_scaling_contract                 = module.platform.rds_read_scaling_contract' 'stacks/environment/outputs.tf'
require_text 'rds_alarm_contract                        = module.platform.rds_alarm_contract' 'stacks/environment/outputs.tf'
require_text 'sid       = "AllowCloudWatchAlarmPublish"' 'modules/observability/main.tf'
require_text 'sid       = "AllowRDSEventPublish"' 'modules/observability/main.tf'
require_text 'sid       = "AllowBackupPublish"' 'modules/observability/main.tf'
require_text 'cloudwatch = "arn:${data.aws_partition.current.partition}:cloudwatch:${data.aws_region.current.region}:${data.aws_caller_identity.current.account_id}:alarm:${var.name_prefix}-*"' 'modules/observability/main.tf'
require_text 'rds        = "arn:${data.aws_partition.current.partition}:rds:${data.aws_region.current.region}:${data.aws_caller_identity.current.account_id}:db:${var.name_prefix}-postgresql"' 'modules/observability/main.tf'
require_text 'backup     = "arn:${data.aws_partition.current.partition}:backup:${data.aws_region.current.region}:${data.aws_caller_identity.current.account_id}:backup-vault:${var.name_prefix}-vault"' 'modules/observability/main.tf'
require_text 'identifiers = ["cloudwatch.amazonaws.com"]' 'modules/observability/main.tf'
require_text 'identifiers = ["events.rds.amazonaws.com"]' 'modules/observability/main.tf'
require_text 'identifiers = ["backup.amazonaws.com"]' 'modules/observability/main.tf'
require_text 'values   = [local.alert_source_arns.cloudwatch]' 'modules/observability/main.tf'
require_text 'values   = [local.alert_source_arns.rds]' 'modules/observability/main.tf'
require_text 'values   = [local.alert_source_arns.backup]' 'modules/observability/main.tf'
require_text 'depends_on  = [aws_sns_topic_policy.alerts]' 'modules/observability/outputs.tf'
forbid_text 'identifiers = ["rds.amazonaws.com"]' 'modules/observability/main.tf'
forbid_text 'identifiers = ["events.amazonaws.com"]' 'modules/observability/main.tf'
require_file 'modules/api-edge-security/main.tf'
require_file 'modules/api-edge-security/variables.tf'
require_file 'modules/api-edge-security/outputs.tf'
require_text 'resource "aws_wafv2_web_acl" "api"' 'modules/api-edge-security/main.tf'
require_text 'scope       = "REGIONAL"' 'modules/api-edge-security/main.tf'
require_text 'default_action {' 'modules/api-edge-security/main.tf'
require_text 'AWSManagedRulesAmazonIpReputationList' 'modules/api-edge-security/main.tf'
require_text 'AWSManagedRulesCommonRuleSet' 'modules/api-edge-security/main.tf'
require_text 'AWSManagedRulesKnownBadInputsRuleSet' 'modules/api-edge-security/main.tf'
require_text 'AWSManagedRulesSQLiRuleSet' 'modules/api-edge-security/main.tf'
require_text 'name     = "launch-rate-limit"' 'modules/api-edge-security/main.tf'
require_text 'name     = "spin-rate-limit"' 'modules/api-edge-security/main.tf'
require_text 'name     = "public-api-rate-limit"' 'modules/api-edge-security/main.tf'
require_text 'name     = "public-healthz-block"' 'modules/api-edge-security/main.tf'
require_text 'search_string         = "/healthz"' 'modules/api-edge-security/main.tf'
require_text 'response_code = 404' 'modules/api-edge-security/main.tf'
require_count 3 'rate_based_statement {' 'modules/api-edge-security/main.tf'
require_count 3 'evaluation_window_sec = 60' 'modules/api-edge-security/main.tf'
require_count 3 'aggregate_key_type    = "IP"' 'modules/api-edge-security/main.tf'
require_count 9 'positional_constraint = "EXACTLY"' 'modules/api-edge-security/main.tf'
require_count 4 'positional_constraint = "STARTS_WITH"' 'modules/api-edge-security/main.tf'
require_count 4 'and_statement {' 'modules/api-edge-security/main.tf'
require_count 2 'search_string         = "/client/"' 'modules/api-edge-security/main.tf'
require_text 'search_string         = "/client/v1/spins"' 'modules/api-edge-security/main.tf'
require_count 2 'search_string         = "/operator/"' 'modules/api-edge-security/main.tf'
require_text 'search_string         = "/operator/v1/launches"' 'modules/api-edge-security/main.tf'
require_count 3 'search_string         = "POST"' 'modules/api-edge-security/main.tf'
require_text 'search_string         = "GET"' 'modules/api-edge-security/main.tf'
require_text 'search_string         = "OPTIONS"' 'modules/api-edge-security/main.tf'
require_text 'for_each = toset(["GET", "OPTIONS", "POST"])' 'modules/api-edge-security/main.tf'
require_text 'limit                 = var.rate_limits.public_requests_per_minute' 'modules/api-edge-security/main.tf'
require_text 'limit                 = var.rate_limits.spin_requests_per_minute' 'modules/api-edge-security/main.tf'
require_text 'limit                 = var.rate_limits.launch_requests_per_minute' 'modules/api-edge-security/main.tf'
require_text 'variable "rate_rule_rollouts"' 'modules/api-edge-security/variables.tf'
require_count 2 'toset(["launch-rate-limit", "public-api-rate-limit", "spin-rate-limit"])' 'modules/api-edge-security/variables.tf'
require_text 'rollout.action == "count" && rollout.evidence_reference == "observation-pending"' 'modules/api-edge-security/variables.tf'
require_text 'rollout.action == "block"' 'modules/api-edge-security/variables.tf'
require_text 'variable "header_size_rule_rollout"' 'modules/api-edge-security/variables.tf'
require_text 'var.header_size_rule_rollout.action == "count"' 'modules/api-edge-security/variables.tf'
require_text 'var.header_size_rule_rollout.action == "block"' 'modules/api-edge-security/variables.tf'
require_text 'for_each = var.header_size_rule_rollout.action == "count" ? [1] : []' 'modules/api-edge-security/main.tf'
require_text 'for_each = var.header_size_rule_rollout.action == "block" ? [1] : []' 'modules/api-edge-security/main.tf'
require_count 6 'for_each = var.rate_rule_rollouts[' 'modules/api-edge-security/main.tf'
require_count 3 '].action == "count" ? [1] : []' 'modules/api-edge-security/main.tf'
require_count 3 '].action == "block" ? [1] : []' 'modules/api-edge-security/main.tf'
require_count 3 'response_code = 429' 'modules/api-edge-security/main.tf'
require_count 3 'name  = "Retry-After"' 'modules/api-edge-security/main.tf'
require_count 3 'value = "30"' 'modules/api-edge-security/main.tf'
require_count 3 'name  = "Access-Control-Allow-Origin"' 'modules/api-edge-security/main.tf'
require_count 3 'name  = "Access-Control-Expose-Headers"' 'modules/api-edge-security/main.tf'
require_count 3 'name  = "X-RGS-Edge-Error"' 'modules/api-edge-security/main.tf'
require_count 3 'value = "Retry-After, X-RGS-Edge-Error"' 'modules/api-edge-security/main.tf'
require_count 3 'value = "RATE_LIMITED"' 'modules/api-edge-security/main.tf'
require_text 'low_rate_rule_method         = "POST"' 'modules/api-edge-security/outputs.tf'
require_text 'public_rate_rule_methods     = ["GET", "OPTIONS", "POST"]' 'modules/api-edge-security/outputs.tf'
require_text 'variable "managed_rule_rollout"' 'modules/api-edge-security/variables.tf'
require_text 'var.managed_rule_rollout.action == "count"' 'modules/api-edge-security/variables.tf'
require_text 'var.managed_rule_rollout.action == "block"' 'modules/api-edge-security/variables.tf'
require_text 'var.managed_rule_rollout.evidence_reference == "observation-pending"' 'modules/api-edge-security/variables.tf'
require_text '^s3://[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]/[^?#]+\\?versionId=[A-Za-z0-9._~+/=-]{1,1024}#[0-9a-f]{64}$' 'modules/api-edge-security/variables.tf'
require_count 3 '^s3://[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]/[^?#]+\\?versionId=[A-Za-z0-9._~+/=-]{1,1024}#[0-9a-f]{64}$' 'modules/api-edge-security/variables.tf'
require_text 'for_each = var.managed_rule_rollout.action == "count" ? [1] : []' 'modules/api-edge-security/main.tf'
require_text 'for_each = var.managed_rule_rollout.action == "block" ? [1] : []' 'modules/api-edge-security/main.tf'
require_count 2 'size_constraint_statement {' 'modules/api-edge-security/main.tf'
require_count 2 'size                = 8192' 'modules/api-edge-security/main.tf'
require_count 2 'oversize_handling = "MATCH"' 'modules/api-edge-security/main.tf'
require_text 'response_code = 413' 'modules/api-edge-security/main.tf'
require_text 'response_code = 431' 'modules/api-edge-security/main.tf'
require_text 'resource "aws_wafv2_web_acl_logging_configuration" "api"' 'modules/api-edge-security/main.tf'
require_text 'default_behavior = "DROP"' 'modules/api-edge-security/main.tf'
require_text 'action = "BLOCK"' 'modules/api-edge-security/main.tf'
require_text 'action = "COUNT"' 'modules/api-edge-security/main.tf'
require_text 'name = "authorization"' 'modules/api-edge-security/main.tf'
require_text 'name = "signature"' 'modules/api-edge-security/main.tf'
require_text 'name = "signature-input"' 'modules/api-edge-security/main.tf'
require_text 'name = "idempotency-key"' 'modules/api-edge-security/main.tf'
require_text 'query_string {}' 'modules/api-edge-security/main.tf'
require_count 9 'sampled_requests_enabled   = false' 'modules/api-edge-security/main.tf'
forbid_text 'sampled_requests_enabled   = true' 'modules/api-edge-security/main.tf'
require_text 'version     = var.managed_rule_versions[rule.key]' 'modules/api-edge-security/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "waf_blocked_requests"' 'modules/api-edge-security/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "waf_allowed_requests"' 'modules/api-edge-security/main.tf'
require_count 2 'namespace           = "AWS/WAFV2"' 'modules/api-edge-security/main.tf'
require_count 2 'alarm_actions       = [var.alert_topic_arn]' 'modules/api-edge-security/main.tf'
require_count 2 'ok_actions          = [var.alert_topic_arn]' 'modules/api-edge-security/main.tf'
require_count 2 'WebACL = local.web_acl_metric' 'modules/api-edge-security/main.tf'
forbid_text 'WebACL = local.web_acl_name' 'modules/api-edge-security/main.tf'
require_text 'authoritative_public_entry   = "internet-facing-alb"' 'modules/api-edge-security/outputs.tf'
require_text 'cloudfront_is_api_proxy      = false' 'modules/api-edge-security/outputs.tf'
require_text 'origin_bypass_model          = "not-applicable-alb-is-authoritative-origin"' 'modules/api-edge-security/outputs.tf'
require_text 'application_body_limit_bytes = 8192' 'modules/api-edge-security/outputs.tf'
require_text 'oversized_body_action        = "BLOCK_AT_WAF_AND_APPLICATION"' 'modules/api-edge-security/outputs.tf'
require_text 'public_health_path           = "/healthz"' 'modules/api-edge-security/outputs.tf'
require_text 'public_health_path_action    = "BLOCK_AT_WAF"' 'modules/api-edge-security/outputs.tf'
require_text 'alb_target_health_port       = 8081' 'modules/api-edge-security/outputs.tf'
require_text 'required_path_rule_names     = ["public-healthz-block", "public-protocol-surface-block"]' 'modules/api-edge-security/outputs.tf'
require_text 'allowed_public_path_prefixes = ["/client/", "/operator/"]' 'modules/api-edge-security/outputs.tf'
require_text 'allowed_public_methods       = ["GET", "OPTIONS", "POST"]' 'modules/api-edge-security/outputs.tf'
require_text 'web_acl_metric_name          = local.web_acl_metric' 'modules/api-edge-security/outputs.tf'
require_text 'managed_rule_rollout  = var.managed_rule_rollout' 'modules/api-edge-security/outputs.tf'
require_text 'rate_rule_rollouts    = var.rate_rule_rollouts' 'modules/api-edge-security/outputs.tf'
require_text 'header_size_rule_rollout     = var.header_size_rule_rollout' 'modules/api-edge-security/outputs.tf'
require_text 'query_string_redacted        = true' 'modules/api-edge-security/outputs.tf'
require_text 'sampled_requests_enabled     = false' 'modules/api-edge-security/outputs.tf'
require_text 'evidence_kms_key_arn         = var.evidence_kms_key_arn' 'modules/api-edge-security/outputs.tf'
require_text 'managed_rule_versions = var.managed_rule_versions' 'modules/api-edge-security/outputs.tf'
require_text 'variable "managed_rule_versions"' 'modules/api-edge-security/variables.tf'
require_text 'variable "evidence_kms_key_arn"' 'modules/api-edge-security/variables.tf'
require_text 'module "api_edge_security" {' 'stacks/application-platform/main.tf'
require_text 'public_requests_per_minute = number' 'stacks/application-platform/variables.tf'
require_text 'spin_requests_per_minute   = number' 'stacks/application-platform/variables.tf'
require_text 'launch_requests_per_minute = number' 'stacks/application-platform/variables.tf'
require_text 'variable "api_waf_rate_rule_rollouts"' 'stacks/application-platform/variables.tf'
require_text 'rate_rule_rollouts       = var.api_waf_rate_rule_rollouts' 'stacks/application-platform/main.tf'
require_text 'variable "api_waf_header_size_rule_rollout"' 'stacks/application-platform/variables.tf'
require_text 'header_size_rule_rollout = var.api_waf_header_size_rule_rollout' 'stacks/application-platform/main.tf'
require_text 'managed_rule_versions    = var.api_waf_managed_rule_versions' 'stacks/application-platform/main.tf'
require_text 'evidence_kms_key_arn     = var.waf_rollout_evidence_kms_key_arn' 'stacks/application-platform/main.tf'
require_text 'api_edge_security        = module.api_edge_security.contract' 'stacks/application-platform/outputs.tf'
require_text 'api_waf_web_acl_arn                       = module.platform.api_waf_web_acl_arn' 'stacks/environment/outputs.tf'
require_text 'waf_rate_limit_per_minute = var.cloudfront_waf_rate_limit_per_minute' 'stacks/application-platform/main.tf'
require_text 'waf_rate_rule_rollout     = var.cloudfront_waf_rate_rule_rollout' 'stacks/application-platform/main.tf'
require_text 'waf_log_group_name        = var.cloudfront_waf_log_group_name' 'stacks/application-platform/main.tf'
require_text 'waf_managed_rule_rollout  = var.cloudfront_waf_managed_rule_rollout' 'stacks/application-platform/main.tf'
require_text 'variable "waf_managed_rule_rollout"' 'modules/web-edge/variables.tf'
require_text 'variable "waf_rate_rule_rollout"' 'modules/web-edge/variables.tf'
require_text 'var.waf_rate_rule_rollout.action == "count"' 'modules/web-edge/variables.tf'
require_text 'var.waf_rate_rule_rollout.action == "block"' 'modules/web-edge/variables.tf'
require_count 2 '^s3://[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]/[^?#]+\\?versionId=[A-Za-z0-9._~+/=-]{1,1024}#[0-9a-f]{64}$' 'modules/web-edge/variables.tf'
require_text 'rate_rule_rollout               = var.waf_rate_rule_rollout' 'modules/web-edge/outputs.tf'
require_text 'query_string_redacted        = true' 'modules/web-edge/outputs.tf'
require_text 'sampled_requests_enabled     = false' 'modules/web-edge/outputs.tf'
require_text 'web_acl_metric_name          = replace("${var.name_prefix}-web", "-", "_")' 'modules/web-edge/outputs.tf'
require_text 'rule_metric_names = {' 'modules/web-edge/outputs.tf'
require_text 'evidence_kms_key_arn  = var.waf_evidence_kms_key_arn' 'modules/web-edge/outputs.tf'
require_text 'managed_rule_versions           = var.waf_managed_rule_versions' 'modules/web-edge/outputs.tf'
require_text 'variable "waf_managed_rule_versions"' 'modules/web-edge/variables.tf'
require_text 'variable "waf_evidence_kms_key_arn"' 'modules/web-edge/variables.tf'
require_text 'var.waf_managed_rule_rollout.action == "count"' 'modules/web-edge/variables.tf'
require_text 'var.waf_managed_rule_rollout.action == "block"' 'modules/web-edge/variables.tf'
require_text 'managed_rule_rollout            = var.waf_managed_rule_rollout' 'modules/web-edge/outputs.tf'
require_text 'waf_managed_rule_versions = var.cloudfront_waf_managed_rule_versions' 'stacks/application-platform/main.tf'
require_text 'waf_evidence_kms_key_arn  = var.waf_rollout_evidence_kms_key_arn' 'stacks/application-platform/main.tf'
require_text 'authoritative_public_entry   = "cloudfront"' 'modules/web-edge/outputs.tf'
require_text 'origin_type                  = "private-s3-oac"' 'modules/web-edge/outputs.tf'
require_text 'origin_public_access_blocked = true' 'modules/web-edge/outputs.tf'
require_text 'api_proxy                    = false' 'modules/web-edge/outputs.tf'
require_text 'web_acl_scope                = "CLOUDFRONT"' 'modules/web-edge/outputs.tf'
require_text 'waf_ownership                = "enterprise-platform"' 'modules/web-edge/outputs.tf'
require_text 'route53_alias_ownership         = "enterprise-platform"' 'modules/web-edge/outputs.tf'
require_text 'cloudfront_edge_security = module.web_edge.edge_security_contract' 'stacks/application-platform/outputs.tf'
require_text 'cloudfront_waf_web_acl_arn                = module.platform.cloudfront_waf_web_acl_arn' 'stacks/environment/outputs.tf'
require_text 'output "release_response_function_arn"' 'modules/web-edge/outputs.tf'
require_text 'output "origin_access_control_id"' 'modules/web-edge/outputs.tf'
require_text 'output "cache_policy_id"' 'modules/web-edge/outputs.tf'
require_text 'output "log_bucket_domain_name"' 'modules/web-edge/outputs.tf'
require_text 'value = module.web_edge.release_response_function_arn' 'stacks/application-platform/outputs.tf'
require_text 'value = module.web_edge.release_response_function_name' 'stacks/application-platform/outputs.tf'
require_text 'cloudfront_release_response_function_arn  = module.platform.cloudfront_release_response_function_arn' 'stacks/environment/outputs.tf'
require_text 'cloudfront_release_response_function_name = module.platform.cloudfront_release_response_function_name' 'stacks/environment/outputs.tf'
require_text 'cloudfront_origin_access_control_id' 'stacks/environment/outputs.tf'
require_text 'cloudfront_cache_policy_id' 'stacks/environment/outputs.tf'
require_text 'cloudfront_log_bucket_domain_name' 'stacks/environment/outputs.tf'
require_text 'observability_alert_publishers = {' 'modules/kms/main.tf'
require_text 'alert_topic_arn = "arn:${data.aws_partition.current.partition}:sns:${data.aws_region.current.region}:${data.aws_caller_identity.current.account_id}:${var.name_prefix}-alerts"' 'modules/kms/main.tf'
require_text 'principal  = "cloudwatch.amazonaws.com"' 'modules/kms/main.tf'
require_text 'principal  = "events.rds.amazonaws.com"' 'modules/kms/main.tf'
require_text 'principal  = "backup.amazonaws.com"' 'modules/kms/main.tf'
require_text 'source_arn = "arn:${data.aws_partition.current.partition}:cloudwatch:${data.aws_region.current.region}:${data.aws_caller_identity.current.account_id}:alarm:${var.name_prefix}-*"' 'modules/kms/main.tf'
require_text 'source_arn = "arn:${data.aws_partition.current.partition}:rds:${data.aws_region.current.region}:${data.aws_caller_identity.current.account_id}:db:${var.name_prefix}-postgresql"' 'modules/kms/main.tf'
require_text 'source_arn = "arn:${data.aws_partition.current.partition}:backup:${data.aws_region.current.region}:${data.aws_caller_identity.current.account_id}:backup-vault:${var.name_prefix}-vault"' 'modules/kms/main.tf'
require_count 2 'actions   = ["kms:Decrypt", "kms:GenerateDataKey*"]' 'modules/kms/main.tf'
require_text 'identifiers = ["sns.amazonaws.com"]' 'modules/kms/main.tf'
require_text 'variable = "kms:EncryptionContext:aws:sns:topicArn"' 'modules/kms/main.tf'
require_text 'values   = [local.alert_topic_arn]' 'modules/kms/main.tf'
require_text 'transit_encryption_mode    = "required"' 'modules/cache/main.tf'
require_text 'AuthoritativeEconomicState = "false"' 'modules/cache/main.tf'
require_text '"7" = "valkey7"' 'modules/cache/main.tf'
require_text '"8" = "valkey8"' 'modules/cache/main.tf'
require_text '"9" = "valkey9"' 'modules/cache/main.tf'
require_text 'resource "aws_elasticache_parameter_group" "noeviction"' 'modules/cache/main.tf'
require_text 'family      = local.valkey_parameter_group_family' 'modules/cache/main.tf'
require_text 'name  = "maxmemory-policy"' 'modules/cache/main.tf'
require_text 'value = "noeviction"' 'modules/cache/main.tf'
require_text 'parameter_group_name = aws_elasticache_parameter_group.noeviction.name' 'modules/cache/main.tf'
require_count 2 'resource "aws_elasticache_user" "rate_limiter_' 'modules/cache/main.tf'
require_text 'passwords_wo  = var.valkey_password_a' 'modules/cache/main.tf'
require_text 'passwords_wo  = var.valkey_password_b' 'modules/cache/main.tf'
require_text 'passwords_wo_version = var.valkey_password_version_a' 'modules/cache/main.tf'
require_text 'passwords_wo_version = var.valkey_password_version_b' 'modules/cache/main.tf'
require_count 2 'on ~rgs:shared-admission:v2:* -@all +evalsha +eval +get +pttl +set +time +mset +pexpire +ping +hello +auth +client|setname +client|setinfo' 'modules/cache/main.tf'
forbid_text '~rgs:shared-admission:v1:*' 'modules/cache/main.tf'
forbid_text '+hmget ' 'modules/cache/main.tf'
forbid_text '+hset ' 'modules/cache/main.tf'
forbid_text '+@read' 'modules/cache/main.tf'
forbid_text '+@write' 'modules/cache/main.tf'
forbid_text '+@all' 'modules/cache/main.tf'
require_text 'acl_schema_version                     = "v2"' 'modules/cache/outputs.tf'
require_text 'acl_schema_transition                  = "maintenance-quiesced"' 'modules/cache/outputs.tf'
require_text 'acl_schema_migration_requires_quiesced = true' 'modules/cache/outputs.tf'
require_text 'acl_schema_rolling_compatible          = false' 'modules/cache/outputs.tf'
require_text 'acl_schema_dual_permissions_allowed    = false' 'modules/cache/outputs.tf'
require_text '"stop-new-intents"' 'modules/cache/outputs.tf'
require_text '"drain-old-api-pods"' 'modules/cache/outputs.tf'
require_text '"apply-v2-acl"' 'modules/cache/outputs.tf'
require_text '"start-v2-runtime"' 'modules/cache/outputs.tf'
require_text '"verify-v2-shared-admission"' 'modules/cache/outputs.tf'
require_text '"resume-new-intents"' 'modules/cache/outputs.tf'
require_text 'valkey_rotation_contract        = module.cache.rotation_contract' 'stacks/application-platform/outputs.tf'
require_text 'valkey_replication_group_id               = module.platform.valkey_replication_group_id' 'stacks/environment/outputs.tf'
require_text 'valkey_parameter_group_name               = module.platform.valkey_parameter_group_name' 'stacks/environment/outputs.tf'
require_text 'valkey_maxmemory_policy                   = module.platform.valkey_maxmemory_policy' 'stacks/environment/outputs.tf'
require_text 'aws_elasticache_user.rate_limiter_a.user_id' 'modules/cache/main.tf'
require_text 'aws_elasticache_user.rate_limiter_b.user_id' 'modules/cache/main.tf'
require_text 'active_password  = var.valkey_active_slot == "a" ? var.valkey_password_a : var.valkey_password_b' 'modules/cache/main.tf'
require_text 'sha256(var.valkey_password_a) == var.valkey_password_fingerprint_a' 'modules/cache/main.tf'
require_text 'sha256(var.valkey_password_b) == var.valkey_password_fingerprint_b' 'modules/cache/main.tf'
require_text 'sha256(var.shared_admission_hmac_key) == var.shared_admission_hmac_key_fingerprint' 'modules/cache/main.tf'
require_text 'var.valkey_hmac_maintenance_approval.bucket_reset_accepted' 'modules/cache/variables.tf'
require_text 'var.valkey_hmac_maintenance_approval.evidence_reference.bucket' 'modules/cache/variables.tf'
require_text 'var.valkey_hmac_maintenance_approval.evidence_reference.key' 'modules/cache/variables.tf'
require_text 'var.valkey_hmac_maintenance_approval.evidence_reference.version_id' 'modules/cache/variables.tf'
require_text '^[A-Za-z0-9._~+/=-]{1,1024}$' 'modules/cache/variables.tf'
require_text 'var.valkey_hmac_maintenance_approval.evidence_reference.sha256' 'modules/cache/variables.tf'
require_text 'target_identity = {' 'modules/cache/main.tf'
require_text 'kubernetes_namespace = var.application_namespace' 'modules/cache/main.tf'
require_text 'helm_release_name    = var.helm_release_name' 'modules/cache/main.tf'
require_count 2 'can(regex("^[!-~]+$", var.valkey_password_' 'modules/cache/variables.tf'
require_count 2 '!can(regex("[,\\\"/@]", var.valkey_password_' 'modules/cache/variables.tf'
require_text '    username = local.active_user_name' 'modules/cache/main.tf'
require_text '(var.valkey_active_slot == "a" && var.secret_version % 2 == 1)' 'modules/cache/main.tf'
require_text '(var.valkey_active_slot == "b" && var.secret_version % 2 == 0)' 'modules/cache/main.tf'
require_text 'local.slots_requiring_reset_approval == toset(keys(var.valkey_password_reset_approvals))' 'modules/cache/main.tf'
require_text 'approval.old_slot_connections_drained &&' 'modules/cache/variables.tf'
require_text 'approval.hmac_key_unchanged &&' 'modules/cache/variables.tf'
require_text 'approval.live_evidence_reference' 'modules/cache/variables.tf'
require_text 'old_slot_reset_requires_live_evidence         = true' 'modules/cache/outputs.tf'
require_text 'hmac_bucket_reset_requires_separate_change    = true' 'modules/cache/outputs.tf'
require_text 'hmac_maintenance_requires_zero_replicas' 'modules/cache/outputs.tf'
require_text 'hmac_maintenance_forbids_parallel_rollout' 'modules/cache/outputs.tf'
require_text 'hmac_maintenance_single_attested_plan         = true' 'modules/cache/outputs.tf'
require_text 'hmac_maintenance_exit_requires_separate_plan  = true' 'modules/cache/outputs.tf'
require_text 'hmac_maintenance_attestation_schema           = "slots-game/hmac-quiesce-attestation/v1"' 'modules/cache/outputs.tf'
require_text 'hmac_maintenance_persistent_lock_name' 'modules/cache/outputs.tf'
require_text 'acl_command_profile                    = "v2-economic"' 'modules/cache/outputs.tf'
require_text 'application_release_allowed                   = var.valkey_rotation_mode != "hmac-maintenance"' 'modules/cache/outputs.tf'
require_text 'maintenance_in_progress                       = var.valkey_rotation_mode == "hmac-maintenance"' 'modules/cache/outputs.tf'
require_text '禁止重置当前活动槽；一次 apply 只能准备唯一非活动槽' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'assert(version_changed_slots == [inactive_slot],' 'scripts/verify-valkey-rotation-plan.rb'
require_text '切换活动槽的同一次 apply 禁止修改任何密码' 'scripts/verify-valkey-rotation-plan.rb'
require_text '普通 A/B 密码轮换禁止改变 HMAC' 'scripts/verify-valkey-rotation-plan.rb'
require_text '用 tfvars 自证后重置活动 A 槽' 'scripts/test-valkey-rotation-plan.rb'
require_text '进入 HMAC 维护的同一个保存 plan 必须完成换 key' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'assert(!evidence_payload.nil?, "HMAC 单计划维护缺少 --evidence 静默证据")' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'assert(target == before.fetch("target_identity")' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'expires_at - observed_at <= 3600' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'assert(expires_at > now, "HMAC 静默证据已过期")' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'api[key] == 0' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'worker["ready"] == worker["desired"]' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'HPA 恢复 spec SHA-256 与 manifest 不一致' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'lock["name"] == "slots-hmac-maintenance-lock"' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'Digest::SHA256.hexdigest(raw) == reference.fetch("sha256")' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'arguments.on("--evidence FILE"' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'after_unknown.fetch("input", false)' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'HMAC_SECRET_REPLACEMENT_ACTIONS = [["create", "delete"]].freeze' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'HMAC_SECRET_VERSION_REPLACEMENT_ACTIONS = [["delete", "create"]].freeze' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'actual_addresses.sort == expected_addresses.sort' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'plan 的非 no-op 资源集合不符合精确 allowlist' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'HMAC 维护 Secret 替换混入普通配置变化' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'HMAC 维护 SecretVersion 替换混入普通配置变化' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'PRE_ECONOMIC_SHARED_ADMISSION_ACL' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'assert(transition == :hmac_entry, "Valkey v1 keyspace 迁移只能进入有静默证据的 HMAC 维护计划")' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'assert(transition == :steady, "Valkey v2 economic ACL 追加只能在 steady 计划中先于新 runtime 应用")' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'Valkey ACL schema 迁移必须在同一计划精确更新 A/B 两个用户' 'scripts/verify-valkey-rotation-plan.rb'
require_text 'steady plan 禁止迁移 ACL schema' 'scripts/test-valkey-rotation-plan.rb'
require_text 'steady 计划先行追加 v2 economic ACL 且保持旧 runtime 兼容' 'scripts/test-valkey-rotation-plan.rb'
require_text 'v2 economic ACL 追加禁止只更新单一凭据槽' 'scripts/test-valkey-rotation-plan.rb'
require_text 'v2 economic ACL 追加拒绝未知或 A/B 不一致前态' 'scripts/test-valkey-rotation-plan.rb'
require_text 'v2 economic ACL 追加拒绝额外命令或 A/B 不一致后态' 'scripts/test-valkey-rotation-plan.rb'
require_text 'v2 economic ACL 追加禁止混入密码轮换' 'scripts/test-valkey-rotation-plan.rb'
require_text 'API 静默证据绑定的 HMAC 入口同时精确迁移 ACL v1 到 v2' 'scripts/test-valkey-rotation-plan.rb'
require_text '首次 A 到 B 切换同时更换 HMAC' 'scripts/test-valkey-rotation-plan.rb'
require_text '单个已保存 plan 内执行受证据绑定的 HMAC 维护' 'scripts/test-valkey-rotation-plan.rb'
require_text 'HMAC 入口夹带 RDS 变化' 'scripts/test-valkey-rotation-plan.rb'
require_text 'HMAC 入口夹带 EKS 变化' 'scripts/test-valkey-rotation-plan.rb'
require_text 'HMAC 入口夹带 IAM 变化' 'scripts/test-valkey-rotation-plan.rb'
require_text 'HMAC 入口夹带网络变化' 'scripts/test-valkey-rotation-plan.rb'
require_text 'HMAC 入口夹带其他 Secret 变化' 'scripts/test-valkey-rotation-plan.rb'
require_text 'HMAC 出口夹带网络变化' 'scripts/test-valkey-rotation-plan.rb'
require_text 'API 实际仍有 Pod' 'scripts/test-valkey-rotation-plan.rb'
require_text '证据已过期' 'scripts/test-valkey-rotation-plan.rb'
forbid_text 'application_replicas_scaled_to_zero' 'modules/cache/variables.tf'
forbid_text 'parallel_rollout_forbidden' 'modules/cache/variables.tf'
forbid_text 'live_evidence_reference             = string' 'modules/cache/variables.tf'
forbid_text 'variable "valkey_password"' 'modules/cache/variables.tf'
forbid_text 'var.valkey_password)' 'modules/cache/main.tf'
forbid_text '+script|load' 'modules/cache/main.tf'
forbid_text '~ratelimit:*' 'modules/cache/main.tf'
forbid_text '~dedupe:*' 'modules/cache/main.tf'
require_text 'secret_string_wo = jsonencode({' 'modules/cache/main.tf'
require_text 'secret_string_wo_version = var.secret_version' 'modules/cache/main.tf'
require_text 'base64encode(base64decode(var.shared_admission_hmac_key)) == var.shared_admission_hmac_key' 'modules/cache/variables.tf'
require_count 9 'CacheClusterId = "${aws_elasticache_replication_group.this.id}-${format("%03d", count.index + 1)}"' 'modules/cache/main.tf'
require_text 'metric_name         = "CommandAuthorizationFailures"' 'modules/cache/main.tf'
require_text 'metric_name         = "KeyAuthorizationFailures"' 'modules/cache/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "engine_cpu_utilization"' 'modules/cache/main.tf'
require_text 'metric_name         = "EngineCPUUtilization"' 'modules/cache/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "database_capacity_usage"' 'modules/cache/main.tf'
require_text 'metric_name         = "DatabaseCapacityUsageCountedForEvictPercentage"' 'modules/cache/main.tf'
require_text 'ReplicationGroupId = aws_elasticache_replication_group.this.id' 'modules/cache/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "current_connections"' 'modules/cache/main.tf'
require_text 'metric_name         = "CurrConnections"' 'modules/cache/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "traffic_management_active"' 'modules/cache/main.tf'
require_text 'metric_name         = "TrafficManagementActive"' 'modules/cache/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "replication_lag"' 'modules/cache/main.tf'
require_text 'metric_name         = "ReplicationLag"' 'modules/cache/main.tf'
require_text 'resource "aws_cloudwatch_metric_alarm" "eval_command_latency"' 'modules/cache/main.tf'
require_text 'metric_name         = "EvalBasedCmdsLatency"' 'modules/cache/main.tf'
require_count 6 'datapoints_to_alarm = 2' 'modules/cache/main.tf'
require_count 6 'evaluation_periods  = 3' 'modules/cache/main.tf'
require_count 6 'period              = 60' 'modules/cache/main.tf'
require_count 5 'threshold           = 0' 'modules/cache/main.tf'
require_count 5 'comparison_operator = "GreaterThanThreshold"' 'modules/cache/main.tf'
require_count 10 'treat_missing_data  = "notBreaching"' 'modules/cache/main.tf'
require_count 10 'alarm_actions       = [var.alert_topic_arn]' 'modules/cache/main.tf'
require_count 7 'ok_actions          = [var.alert_topic_arn]' 'modules/cache/main.tf'
require_text 'threshold           = var.valkey_alarm_thresholds.engine_cpu_utilization_percent' 'modules/cache/main.tf'
require_text 'threshold           = var.valkey_alarm_thresholds.database_capacity_usage_counted_for_evict_percent' 'modules/cache/main.tf'
require_text 'threshold           = var.valkey_alarm_thresholds.current_connections' 'modules/cache/main.tf'
require_text 'threshold           = var.valkey_alarm_thresholds.replication_lag_seconds' 'modules/cache/main.tf'
require_text 'threshold           = var.valkey_alarm_thresholds.eval_based_commands_latency_microseconds' 'modules/cache/main.tf'
require_text 'var.valkey_alarm_thresholds.engine_cpu_utilization_percent <= 100' 'modules/cache/variables.tf'
require_text 'var.valkey_alarm_thresholds.database_capacity_usage_counted_for_evict_percent < 100' 'modules/cache/variables.tf'
require_text 'floor(var.valkey_alarm_thresholds.current_connections) == var.valkey_alarm_thresholds.current_connections' 'modules/cache/variables.tf'
require_text 'var.valkey_alarm_thresholds.replication_lag_seconds <= 60' 'modules/cache/variables.tf'
require_text 'floor(var.valkey_alarm_thresholds.eval_based_commands_latency_microseconds) == var.valkey_alarm_thresholds.eval_based_commands_latency_microseconds' 'modules/cache/variables.tf'
require_text 'valkey_alarm_thresholds               = var.valkey_alarm_thresholds' 'stacks/application-platform/main.tf'
require_text 'valkey_alarm_thresholds               = var.configuration.valkey_alarm_thresholds' 'stacks/environment/main.tf'
require_text '该协议迁移禁止作为普通 Helm rolling upgrade' 'README.md'
require_text '`acl_schema_transition=maintenance-quiesced`' 'README.md'
require_text '`acl_schema_rolling_compatible=false`' 'README.md'
require_text '`acl_schema_dual_permissions_allowed=false`' 'README.md'
require_text '删除 API HPA、等待在途请求及旧连接排空，再把 API 缩到零' 'README.md'
require_text 'API 零副本证据、HMAC 更新、Secret 版本精确加二以及 A/B 两个 ACL 的 v1→v2' 'README.md'
require_text '普通 `steady` 或' 'README.md'
require_text '`password-rotation` plan 中出现 ACL 变更会失败关闭' 'README.md'
require_text '只有 canary、钱包状态查询/ACK 绕行和 Worker 恢复全部通过后' 'README.md'
require_text '"rediss://${aws_elasticache_replication_group.this.primary_endpoint_address}:${aws_elasticache_replication_group.this.port}"' 'modules/cache/outputs.tf'
forbid_text 'type = "iam"' 'modules/cache/main.tf'
forbid_text 'elasticache:Connect' 'modules/cache/main.tf'
forbid_text 'aws_eks_pod_identity_association' 'modules/cache/main.tf'
forbid_text 'resource "aws_security_group" "rgs_workload"' 'stacks/application-platform/main.tf'
forbid_text 'resource "aws_security_group" "rate_limiter_workload"' 'stacks/application-platform/main.tf'
require_count 2 'module.eks.cluster_security_group_id' 'stacks/application-platform/main.tf'
require_text 'foundation_apply_is_application_ready = false' 'stacks/application-platform/outputs.tf'
require_text 'private_vpc_runner_required' 'stacks/application-platform/outputs.tf'
require_text 'AutomatedExportReady = "false"' 'modules/archive/main.tf'
require_text 'object_lock_enabled = true' 'modules/archive/main.tf'
require_text 'aws_backup_vault_lock_configuration' 'modules/backup/main.tf'
require_text 'block_public_acls       = true' 'modules/web-edge/main.tf'
forbid_text 'block_public_acls       = false' 'modules/web-edge/main.tf'
require_text 'origin_access_control_origin_type = "s3"' 'modules/web-edge/main.tf'
require_text 'http_version        = "http2and3"' 'modules/web-edge/main.tf'
require_text 'viewer_http_version          = "http2and3"' 'modules/web-edge/outputs.tf'
forbid_text 'frame_options {' 'modules/web-edge/main.tf'
forbid_text 'frame_option = "SAMEORIGIN"' 'modules/web-edge/main.tf'
require_text 'sid       = "DenyUnconditionalReleaseWrites"' 'modules/web-edge/main.tf'
require_text 'actions   = ["s3:PutObject"]' 'modules/web-edge/main.tf'
require_text 'resources = ["${aws_s3_bucket.web.arn}/releases/*"]' 'modules/web-edge/main.tf'
require_text 'variable = "s3:ObjectCreationOperation"' 'modules/web-edge/main.tf'
require_text 'variable = "s3:if-none-match"' 'modules/web-edge/main.tf'
require_text "store.get('active-release')" 'modules/web-edge/release-request.js'
require_text 'Secure; HttpOnly; SameSite=None; Partitioned' 'modules/web-edge/release-response.js'
forbid_text 'SameSite=Strict' 'modules/web-edge/release-response.js'
forbid_text 'SameSite=Lax' 'modules/web-edge/release-response.js'
require_text '`frame-ancestors` CSP 授权跨源运营商 iframe' 'README.md'
require_text '`s3:ObjectCreationOperation` 拒绝 `releases/*` 无条件 `PutObject`' 'README.md'
require_text '发布身份删除权限的 IAM/SCP 收口和真实账号回读仍是' 'README.md'
require_text 'var.backup_enable_vault_lock' 'stacks/application-platform/main.tf'
require_text 'var.rds_multi_az' 'stacks/application-platform/main.tf'
require_text 'ephemeral   = true' 'modules/cache/variables.tf'
require_text 'rgs-shared-admission-v${var.secret_version}' 'modules/cache/main.tf'
require_text 'activeSlotOutput: valkey_active_slot' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'aclUserNamesOutput: valkey_user_names' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'bothUsersAlwaysInUserGroup: true' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'oldSlotResetRequiresLiveEvidence: true' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'hmacBucketContinuityRequiredDuringPasswordRotation: true' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'hmacMaintenanceEntryAndKeyChangeInSingleAttestedPlan: true' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'hmacMaintenanceEvidenceSchema: slots-game/hmac-quiesce-attestation/v1' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'hmacMaintenanceEvidenceMaximumTtlSeconds: 3600' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'hmacMaintenancePersistentLockName: slots-hmac-maintenance-lock' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'hmacMaintenanceExitRequiresSeparatePlan: true' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'maintenanceDeliveryMustStillBePublished: true' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'maintenanceInProgressOutput: maintenance_in_progress' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'hmacMaintenanceNonNoopResourceAllowlist:' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'addressSuffix: module.cache.aws_secretsmanager_secret.shared_admission' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'addressSuffix: module.cache.aws_secretsmanager_secret_version.shared_admission' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'hmacMaintenanceAllowsIamPolicyChanges: false' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'hmacMaintenanceParallelRolloutAllowed: false' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'valkey_rotation_contract' 'stacks/environment/outputs.tf'
require_text 'valkey_rotation_mode' 'stacks/environment/outputs.tf'
require_text 'application_release_allowed' 'stacks/environment/outputs.tf'
require_text 'maintenance_in_progress' 'stacks/environment/outputs.tf'
require_text 'valkey_user_names' 'stacks/environment/outputs.tf'
require_text 'valkey_password_versions' 'stacks/environment/outputs.tf'
require_text 'var.secret_versions[each.key]' 'modules/secrets/main.tf'
require_text 'api-runtime-assets' 'modules/secrets/main.tf'
require_text 'worker-runtime-assets' 'modules/secrets/main.tf'
require_text 'shared_admission_secret_arn_pattern = "arn:${data.aws_partition.current.partition}:secretsmanager:${var.aws_region}:${var.aws_account_id}:secret:${var.shared_admission_secret_name_prefix}-v*"' 'modules/secrets/main.tf'
require_text 'resources = concat(values(aws_secretsmanager_secret.application)[*].arn, [local.shared_admission_secret_arn_pattern])' 'modules/secrets/main.tf'
require_text 'shared_admission_secret_name_prefix = "${local.name_prefix}-rgs-shared-admission"' 'stacks/application-platform/main.tf'
forbid_text 'additional_secret_arns' 'modules/secrets/variables.tf'
forbid_text 'additional_secret_arns' 'stacks/application-platform/main.tf'
forbid_text 'module.cache.secret_arn' 'stacks/application-platform/main.tf'
forbid_text '"runtime-assets"' 'modules/secrets/main.tf'
require_text '九个子网 CIDR 之间不得存在任何重叠。' 'modules/network/main.tf'
require_text 'left_index >= right_index || !try(' 'modules/network/main.tf'
require_text 'local.vpc_network_address' 'modules/network/main.tf'
require_text 'resource "aws_vpc_security_group_egress_rule" "alb_application"' 'modules/network/main.tf'
require_text 'resource "aws_vpc_security_group_egress_rule" "alb_operations_health"' 'modules/network/main.tf'
require_text 'from_port         = 8080' 'modules/network/main.tf'
require_text 'to_port           = 8080' 'modules/network/main.tf'
require_text 'from_port         = 8081' 'modules/network/main.tf'
require_text 'to_port           = 8081' 'modules/network/main.tf'
require_count 2 'cidr_ipv4         = var.vpc_cidr' 'modules/network/main.tf'
require_text 'value       = [8080, 8081]' 'modules/network/outputs.tf'
require_text 'output "public_subnet_cidrs"' 'modules/network/outputs.tf'
require_text 'value = module.network.public_subnet_cidrs' 'stacks/application-platform/outputs.tf'
require_text 'public_subnet_cidrs' 'stacks/environment/outputs.tf'
require_text 'alb_egress_target_ports               = module.network.alb_egress_target_ports' 'stacks/application-platform/outputs.tf'
require_text 'variable "alb_access_log_bucket_name"' 'stacks/application-platform/variables.tf'
require_text 'variable "alb_access_log_prefix"' 'stacks/application-platform/variables.tf'
require_text 'alb_access_logs = {' 'stacks/application-platform/outputs.tf'
require_text 'alb_access_log_bucket_name                = module.platform.alb_access_log_bucket_name' 'stacks/environment/outputs.tf'
require_text 'alb_access_log_prefix                     = module.platform.alb_access_log_prefix' 'stacks/environment/outputs.tf'
require_text '    - albAccessLogBucketName' 'contracts/landing-zone-interface.v1.yaml'
require_text '    - albAccessLogEnvironmentPrefix' 'contracts/landing-zone-interface.v1.yaml'
require_text 'alb_egress_target_ports                   = module.platform.alb_egress_target_ports' 'stacks/environment/outputs.tf'
forbid_text 'ip_protocol       = "-1"' 'modules/network/main.tf'
require_text 'split(":", var.backup_copy_destination_vault_arn)[3] != var.aws_region' 'modules/delivery-contract/variables.tf'
require_text '"cluster-autoscaler"' 'stacks/application-platform/variables.tf'
require_text 'cluster_autoscaler_image_tag' 'stacks/application-platform/outputs.tf'
require_text 'cluster_autoscaler_role_arn' 'stacks/environment/outputs.tf'
require_text 'cluster_autoscaler_inline_policy_name' 'stacks/environment/outputs.tf'
require_text 'application_namespace' 'stacks/environment/outputs.tf'
require_text 'helm_release_name' 'stacks/environment/outputs.tf'
require_text 'id: cluster-autoscaler' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'metrics_server_addon_version = var.eks_addon_versions["metrics-server"]' 'stacks/application-platform/outputs.tf'
require_text 'output "vpc_cni_role_arn"' 'modules/eks/outputs.tf'
require_text 'vpc_cni_network_policy' 'stacks/application-platform/outputs.tf'
require_text 'addon_version   = var.eks_addon_versions["vpc-cni"]' 'stacks/application-platform/outputs.tf'
require_text 'enableNetworkPolicy = "true"' 'stacks/application-platform/outputs.tf'
require_text 'role_arn        = module.eks.vpc_cni_role_arn' 'stacks/application-platform/outputs.tf'
require_text 'id: vpc-cni-network-policy' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'output "cloudwatch_agent_role_arn"' 'modules/observability/outputs.tf'
require_text 'cloudwatch_observability' 'stacks/application-platform/outputs.tf'
require_text 'addon_version   = var.eks_addon_versions["amazon-cloudwatch-observability"]' 'stacks/application-platform/outputs.tf'
require_text 'role_arn        = module.observability.cloudwatch_agent_role_arn' 'stacks/application-platform/outputs.tf'
require_text 'id: amazon-cloudwatch-observability' 'contracts/cluster-addons-interface.v1.yaml'
require_text '        - fluent-bit' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'metrics_server               = "kube-system/metrics-server"' 'stacks/application-platform/outputs.tf'
require_text 'kube_state_metrics           = "monitoring/kube-prometheus-stack-kube-state-metrics"' 'stacks/application-platform/outputs.tf'
require_text 'resource_metrics = "v1beta1.metrics.k8s.io"' 'stacks/application-platform/outputs.tf'
require_text 'kube_state_metrics_release_name = "kube-prometheus-stack"' 'stacks/application-platform/outputs.tf'
require_text 'id: metrics-server' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'requiredApiServiceCondition: Available=True' 'contracts/cluster-addons-interface.v1.yaml'
require_text 'requiredForHpaConditionAlerts: true' 'contracts/cluster-addons-interface.v1.yaml'
forbid_text 'resource "aws_cloudfront_cache_policy" "entry"' 'modules/web-edge/main.tf'

if find "$terraform_root/environments" -name '*.tfvars*' -type f -exec \
  grep -Eil '(password[[:space:]]*=|secret_value[[:space:]]*=|access_key[[:space:]]*=|private_key[[:space:]]*=|auth_token[[:space:]]*=)' {} + |
  grep . >/dev/null; then
  fail 'tfvars 示例中出现 Secret 值字段'
fi

if grep -Ril --include='*.tf' --include='*.tfvars*' --include='*.yaml' --include='*.js' \
  -E '(^|[^A-Za-z])(kafka|msk)([^A-Za-z]|$)' "$terraform_root" >/dev/null; then
  fail '基础设施错误引入 Kafka/MSK 钱包正确性依赖'
fi

printf '%s\n' 'Terraform static contract: passed'
