apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "slots.resourceName" (dict "root" . "suffix" "rgs") }}
  labels:
    {{- include "slots.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: rgs
spec:
  minAvailable: {{ .Values.rgs.pdb.minAvailable }}
  unhealthyPodEvictionPolicy: IfHealthyBudget
  selector:
    matchLabels:
      {{- include "slots.selectorLabels" (dict "root" . "component" "rgs") | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "slots.resourceName" (dict "root" . "suffix" "web") }}
  labels:
    {{- include "slots.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.web.pdb.minAvailable }}
  unhealthyPodEvictionPolicy: IfHealthyBudget
  selector:
    matchLabels:
      {{- include "slots.selectorLabels" (dict "root" . "component" "web") | nindent 6 }}
