apiVersion: v1
kind: Service
metadata:
  name: {{ include "slots.resourceName" (dict "root" . "suffix" "rgs") }}
  labels:
    {{- include "slots.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: rgs
spec:
  type: ClusterIP
  selector:
    {{- include "slots.selectorLabels" (dict "root" . "component" "rgs") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slots.resourceName" (dict "root" . "suffix" "rgs-operations") }}
  labels:
    {{- include "slots.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: rgs-operations
    slots-game.io/metrics-job: slots-rgs
spec:
  type: ClusterIP
  selector:
    {{- include "slots.selectorLabels" (dict "root" . "component" "rgs") | nindent 4 }}
  ports:
    - name: operations
      port: 8081
      targetPort: operations
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slots.resourceName" (dict "root" . "suffix" "web") }}
  labels:
    {{- include "slots.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "slots.selectorLabels" (dict "root" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
