apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slots.resourceName" (dict "root" . "suffix" "rgs") }}
  labels:
    {{- include "slots.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: rgs
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slots.resourceName" (dict "root" . "suffix" "rgs-worker") }}
  labels:
    {{- include "slots.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: rgs-worker
automountServiceAccountToken: false
{{- if .Values.web.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slots.resourceName" (dict "root" . "suffix" "web") }}
  labels:
    {{- include "slots.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
automountServiceAccountToken: false
{{- end }}
