import { describe, expect, it } from "vitest";
import {
  AUDIO_CUES,
  audioBusForCue,
  isLoopAudioCue,
  normalizeAudioCueOptions,
} from "../src/audio/AudioManager";

describe("procedural audio cue model", () => {
  it("routes every semantic cue into one of five mix buses", () => {
    expect(AUDIO_CUES.map((cue) => [cue, audioBusForCue(cue)])).toEqual([
      ["intro.game", "impact"],
      ["ui.splash-continue", "ui"],
      ["ui.button-feedback", "ui"],
      ["ui.click", "ui"],
      ["ui.open", "ui"],
      ["ui.close", "ui"],
      ["reel.start", "reels"],
      ["reel.loop", "reels"],
      ["reel.motor", "reels"],
      ["reel.stop", "reels"],
      ["reel.anticipation", "reels"],
      ["symbol.scatter-land-1", "reels"],
      ["symbol.scatter-land-2", "reels"],
      ["symbol.scatter-land-3", "reels"],
      ["symbol.scatter-land-4", "reels"],
      ["symbol.scatter-land-5", "reels"],
      ["symbol.wild-land", "reels"],
      ["energy.collect", "win"],
      ["pps.level-1", "impact"],
      ["pps.level-2", "impact"],
      ["pps.level-3", "impact"],
      ["pps.level-4", "impact"],
      ["pps.level-5", "impact"],
      ["symbol.lp1", "win"],
      ["symbol.lp2", "win"],
      ["symbol.mp1", "win"],
      ["symbol.mp2", "win"],
      ["symbol.hp1", "win"],
      ["symbol.hp2", "win"],
      ["symbol.wild", "win"],
      ["symbol.scatter-win", "win"],
      ["wheel.spin", "reels"],
      ["wheel.appear", "reels"],
      ["wheel.panel-in", "reels"],
      ["wheel.wait", "reels"],
      ["wheel.award", "reels"],
      ["wheel.king-spin-won", "win"],
      ["wheel.kong-quest-won", "win"],
      ["feature.start", "win"],
      ["free-spins.loop-end", "win"],
      ["free-spins.outro", "win"],
      ["free-spins.music-end", "win"],
      ["big-win.trigger", "win"],
      ["big-win.level-up", "win"],
      ["big-win.end", "win"],
      ["big-win.counter-start", "win"],
      ["big-win.counter-sweetener", "win"],
      ["big-win.counter-tail", "win"],
      ["normal-win.counter-start", "win"],
      ["normal-win.counter-sweetener", "win"],
      ["normal-win.counter-tail", "win"],
      ["win.loss-or-equal", "win"],
      ["win.sting", "win"],
      ["monster.impact", "impact"],
      ["monster.roar", "impact"],
      ["monster.roar-hit", "impact"],
      ["monster.sniff", "impact"],
      ["monster.thump-expand", "impact"],
      ["monster.reel-stretch", "impact"],
      ["monster.feature-activate", "impact"],
      ["vault.unlock-1", "impact"],
      ["vault.unlock-2", "impact"],
      ["vault.unlock-3-plus", "impact"],
      ["vault.anticipation", "impact"],
      ["vault.fly", "impact"],
      ["jackpot.mini", "win"],
      ["jackpot.minor", "win"],
      ["jackpot.major", "win"],
      ["jackpot.mega", "win"],
      ["jackpot.grand", "win"],
      ["payout.win-1", "win"],
      ["payout.win-2", "win"],
      ["payout.win-3", "win"],
      ["payout.win-4", "win"],
      ["payout.win-5", "win"],
      ["payout.win-6", "win"],
      ["payout.win-7", "win"],
      ["payout.win-8", "win"],
      ["ambient.city", "ambient"],
      ["music.free-spins", "ambient"],
      ["music.big-win", "ambient"],
      ["counter.big-win", "ambient"],
      ["counter.normal-generic", "win"],
      ["counter.normal-common", "win"],
    ]);
    expect(new Set(AUDIO_CUES.map(audioBusForCue))).toEqual(
      new Set(["ui", "reels", "win", "impact", "ambient"]),
    );
  });

  it("identifies reel, base-music, and free-spin-music programs as loops", () => {
    expect(AUDIO_CUES.filter(isLoopAudioCue)).toEqual([
      "reel.loop",
      "reel.motor",
      "wheel.wait",
      "ambient.city",
      "music.free-spins",
      "music.big-win",
      "counter.big-win",
      "counter.normal-generic",
      "counter.normal-common",
    ]);
  });

  it("normalizes unsafe scheduling and mix inputs", () => {
    expect(normalizeAudioCueOptions({
      delayMs: -20,
      pan: 4,
      intensity: Number.NaN,
      reducedMotion: true,
    })).toEqual({ delayMs: 0, pan: 1, intensity: 1, reducedMotion: true });
    expect(normalizeAudioCueOptions({ delayMs: 99_000, pan: -4, intensity: -1 })).toEqual({
      delayMs: 10_000,
      pan: -1,
      intensity: 0,
      reducedMotion: false,
    });
  });
});
